import string
import re

### accepted chars and language-specific cleaning function
accepted_chars = string.ascii_lowercase + "àèìòùáéíóúäëïöüñçâêîôû'’· -0123456789" # todo: remove 0-9

def lang_cleaning_text(text):
    text = re.sub(r'-(?![a-zA-ZàèéíòóúüïçÀÈÉÍÒÓÚÜÏÇ])', " ", text)
    text = re.sub(r'(?<![a-zA-ZàèéíòóúüïçÀÈÉÍÒÓÚÜÏÇ])-', " ", text)
    text = re.sub(r'·(?![a-zA-ZàèéíòóúüïçÀÈÉÍÒÓÚÜÏÇ])', " ", text)
    text = re.sub(r'(?<![a-zA-ZàèéíòóúüïçÀÈÉÍÒÓÚÜÏÇ])·', " ", text)
    return text    

### special characters

ordinals = {"℃": "graus Celsius",
            "°C": "graus Celsius",
            "ºC": "graus Celsius",
            "℉": "graus Farenheit",
            "°F": "graus Farenheit",
            "ºF": "graus Farenheit",
            "1r": "primer",
            "1ra": "primera",
            "2n": "segon",
            "2na": "segona",
            "3r": "tercer",
            "3a": "tercera",
            "4t": "quart",
            "4ta": "quarta",
            "5è": "cinquè",
            "5ena": "cinquena",
            "1º": "primer",
            "1ª": "primera",
            "2º": "segon",
            "2ª": "segona",
            "3º": "tercer",
            "3ª": "tercera",
            "4º": "quart",
            "4ª": "quarta",
            "5º": "cinquè",
            "5ª": "cinquena"
            }

currency = {"€": "euros",
    "$": "dòlars",
    "¥": "iens",
    "£": "lliures"}

dots_and_commas = {
    ".": "punt",
    ",": "coma",
}
phisics_and_maths = {  
    "°": "graus",
    "+": "més",
    "=": "igual a",
    "%": "per cent",
    ">": "major que",
    "<": "menor que",
    "%": "per cent",
    "ħ": "constant de Planck reduïda",
    "µ": "micro",
    "𝜆": "Lambda",
    "∑": "sumatori",
    "≈": "aproximadament igual a",
    "≠": "diferent de",
    "≥": "major o igual que",
    "≤": "menor o igual que ",
    "∞": "infinit",
    "√": "arrel quadrada",
    "²": "al quadrat",
    "³": "al cub",
    "×": "multiplicat per",
    "÷": "dividit per",
    "±": "més o menys",
    "∫": "integral",
    "∂": "derivativa parcial",
    "∇": "nabla",
    "≡": "congruent a",
    "≜": "definit com",
    "⁰": "superíndex zero",
    "ⁱ": "superíndex u",
    "ⁿ": "superíndex ena",
    "⁻": "superíndex menys",
    "₀": "subíndex theta",
    "𝑓": "funció efa",
    "𝑥": "ics",
    "ˣ": "ics"}

greek_letters = {

"Α": "alfa",
"Β": "beta",
"Γ": "gamma",
"Δ": "delta",
"Ε": "èpsilon",
"Ζ": "zeta",
"Η": "eta",
"Θ": "theta",
"Ι": "iota",
"Κ": "kappa",
"Λ": "lambda",
"Μ": "mi",
"Ν": "ni",
"Ξ": "ksi",
"Ο": "òmicron",
"Π": "pi",
"Ρ": "ro",
"Σ": "sigma",
"Τ": "tau",
"Υ": "ípsilon",
"Φ": "fi",
"Χ": "khi",
"Ψ": "psi",
"Ω": "omega",

"α": "alfa",
"β": "beta",
"γ": "gamma",
"δ": "delta",
"ε": "èpsilon",
"ζ": "zeta",
"η": "eta",
"θ": "theta",
"ι": "iota",
"κ": "kappa",
"λ": "lambda",
"μ": "mi",
"ν": "ni",
"ξ": "ksi",
"ο": "òmicron",
"π": "pi",
"ρ": "ro",
"σ": "sigma",
"τ": "tau",
"υ": "ípsilon",
"φ": "fi",
"χ": "khi",
"ψ": "psi",
"ω": "omega"}

### more than one character
abr_dict =  {
 'ac': 'abans de Crist',
 'am': 'ante meridiem',
 'adj': 'adjectiu',
 'adm': 'administració',
 'adv': 'adverbi',
 'agr': 'agricultura',
 'ant': 'anterior',
 'aprox': 'aproximadament',
 'arq': 'arquitecte',
 'ass': 'associació',
 'atm': 'atmosfera',
 'aux': 'auxiliar',
 'av': 'avinguda',
 'avda': 'avinguda',
 'batx': 'batxillerat',
 'bibl': 'biblioteca',
 'carr': 'carrer',
 'cat': 'català',
 'cit': 'citat',
 'cm': 'centímetre',
 'coord': 'coordinador',
 'dc': 'després de Crist',
 'd/d': 'dies data',
 'dc': 'dimecres',
 'dep': 'departament',
 'dest': 'destinatari',
 'dg': 'diumenge',
 'disp': 'disposició',
 'dj': 'dijous',
 'dl': 'dilluns',
 'doc': 'document',
 'dr': 'doctor',
 'dra': 'doctora',
 'ds': 'dissabte',
 'dt': 'dimarts',
 'dv': 'divendres',
 'eg': 'exempli gratia',
 'edif': 'edifici',
 'ent': 'entresòl',
 'esp': 'espanyol',
 'etc': 'etcètera',
 'ext': 'exterior',
 'feb': 'febrer',
 'ff': 'fulls',
 'fig': 'figura',
 'fm': 'freqüència modulada',
 'fol': 'foli',
 'fr': 'francès',
 'gr': 'gram',
 'gral': 'general',
 'hab': 'habitació',
 'hm': 'hectòmetres',
 'inst': 'institut',
 'int': 'interior',
 'kg': 'quilograms',
 'km': 'quilòmetres',
 'km/h': 'quilòmetres per hora',
 'mph': 'milles per hora',
 'lat': 'latitud',
 'long': 'longitud',
 'màx': 'màxim',
 'mín': 'mínim',
 'mm': 'mil·límetre',
 'n/d': 'no disponible',
 'n/p': 'no present',
 'núm': 'número',
 'pex': 'per exemple',
 'pm': 'post meridiem',
 'pm': 'post meridiem',
 'pàg': 'pàgina',
 'pd': 'postdata',
 'pl': 'plaça',
 'prof': 'professor',
 'ref': 'referència',
 's/n': 'sense número',
 'seg': 'següent',
 'trad': 'traducció',
 'var': 'variable',
 'vs': 'versus',
 }

acronyms_dict = {"psoe": "pe soe", # acronyms that are not pronounced as a word (in this case, "keep initials", neither letter by letter)
                 "fnac": "efnac",
                 "dgaia": "degaia",
                 "psuc": "pe suc",
                 "psan": "pe san"
}

keep_initials = ["iec", "pime", "unesco", "renfe", "pimes", "afa", "afas", "ser", "tic", "pib", "erto", "mena", "poum", "vox", "ceo", "coi",
                 "oms", "aie", "soc", "pas", "ave", "mes", "macba", "crae", "onu", "fama","acatur", "agbar", "rac", "mat", "acab", "cap",
                 "adif", "dui", "loapa", "pimec", "pac", "bei", "vao", "icub", "faada", "ampa", "uspac", "ustec", "iva", "uci", "cac", "coac", "caoc",
                 "sim", "boe", "cram", "centa", "eta", "sareb",
                 "afes", "once", "affac", "acapps", "cup", "ciu", "acció", "sem", "erc"] # acronyms that are pronounced as a word

# TODO: add roman nums
roman_nums = {"II": "segon",
              "III": "tercer",
              "IIII": "quatre",
              "IV": "quart",  
              "VII": "setè",
              "VIII": "vuitè",
              "IX": "novè",
              "X": "desè",
              }

follow_proper_name = {
    "I": "primer",
    "V": "cinquè",
    "VI": "sisè"
}

letters = {"A": "a",
"B": "be",
"C": "ce",
"D": "de",
"E": "e",
"F": "efa",
"G": "ge",
"H": "hac",
"I": "i",
"J": "jota",
"K": "ca",
"L": "ela",
"M": "ema",
"N": "ena",
"O": "o",
"P": "pe",
"Q": "cu",
"R": "erra",
"S": "essa",
"T": "te",
"U": "u",
"V": "ve",
"W": "ve doble",
"X": "ics",
"Y": "i grega",
"Z": "zeta"}

