import string
import re

onset = ["[bcfgklp]?[l]?[aeiouàáèéíïòóúü]+", "[bcfgkpdt]?[r]?[aeiouàáèéíïòóúü]+", "ny[aeiouàáèéíïòóúü]+", "^psi", "^gno", "^pne", "[bcdfghjklmnopqrstuvwxz]?[aeiouàáèéíïòóúü]+"] # possible syllabic onset + nucleous
coda = ["[lrm]?[bcdfglmpt]?s?", "ny?s?", "[bcçdfghjklmnopqrstuvwxz]?s?"] # possible syllabic coda
    
### special characters

ordinals = {"℃": "graus Celsius",
            "°C": "graus Celsius",
            "ºC": "graus Celsius",
            "℉": "graus Farenheit",
            "°F": "graus Farenheit",
            "ºF": "graus Farenheit",
            "1r": "primer",
            "1ra": "primera",
            "2n": "segon",
            "2na": "segona",
            "3r": "tercer",
            "3a": "tercera",
            "4t": "quart",
            "4ta": "quarta",
            "5è": "cinquè",
            "5ena": "cinquena",
            "1º": "primer",
            "1ª": "primera",
            "2º": "segon",
            "2ª": "segona",
            "3º": "tercer",
            "3ª": "tercera",
            "4º": "quart",
            "4ª": "quarta",
            "5º": "cinquè",
            "5ª": "cinquena"
            }

currency = {"€": "euros",
    "$": "dòlars",
    "¥": "iens",
    "£": "lliures"}

dots_and_commas = {
    ".": "punt",
    ",": "coma",
}
phisics_and_maths = {  
    "°": "graus",
    "+": "més",
    "=": "igual a",
    "%": "per cent",
    ">": "major que",
    "<": "menor que",
    "%": "per cent",
    "ħ": "constant de Planck reduïda",
    "µ": "micro",
    "𝜆": "Lambda",
    "∑": "sumatori",
    "≈": "aproximadament igual a",
    "≠": "diferent de",
    "≥": "major o igual que",
    "≤": "menor o igual que ",
    "∞": "infinit",
    "√": "arrel quadrada",
    "²": "al quadrat",
    "³": "al cub",
    "×": "multiplicat per",
    "÷": "dividit per",
    "±": "més o menys",
    "∫": "integral",
    "∂": "derivativa parcial",
    "∇": "nabla",
    "≡": "congruent a",
    "≜": "definit com",
    "⁰": "superíndex zero",
    "ⁱ": "superíndex u",
    "ⁿ": "superíndex ena",
    "⁻": "superíndex menys",
    "₀": "subíndex theta",
    "𝑓": "funció efa",
    "𝑥": "ics",
    "ˣ": "ics"}

greek_letters = {

"Α": "alfa",
"Β": "beta",
"Γ": "gamma",
"Δ": "delta",
"Ε": "èpsilon",
"Ζ": "zeta",
"Η": "eta",
"Θ": "theta",
"Ι": "iota",
"Κ": "kappa",
"Λ": "lambda",
"Μ": "mi",
"Ν": "ni",
"Ξ": "ksi",
"Ο": "òmicron",
"Π": "pi",
"Ρ": "ro",
"Σ": "sigma",
"Τ": "tau",
"Υ": "ípsilon",
"Φ": "fi",
"Χ": "khi",
"Ψ": "psi",
"Ω": "omega",

"α": "alfa",
"β": "beta",
"γ": "gamma",
"δ": "delta",
"ε": "èpsilon",
"ζ": "zeta",
"η": "eta",
"θ": "theta",
"ι": "iota",
"κ": "kappa",
"λ": "lambda",
"μ": "mi",
"ν": "ni",
"ξ": "ksi",
"ο": "òmicron",
"π": "pi",
"ρ": "ro",
"σ": "sigma",
"τ": "tau",
"υ": "ípsilon",
"φ": "fi",
"χ": "khi",
"ψ": "psi",
"ω": "omega"}

### more than one character
abr_dict =  {
 'aprox': 'aproximadament',
 'avda': 'avinguda',
 'cm': 'centímetre',
 'dr': 'doctor',
 'dra': 'doctora',
 'sr': 'senyor',
 'sra': 'senyora',
 'etc': 'etcètera',
 'fr': 'francès',
 'gr': 'gram',
 'kg': 'quilograms',
 'km': 'quilòmetres',
 'km/h': 'quilòmetres per hora',
 'mph': 'milles per hora',
 'màx': 'màxim',
 'mín': 'mínim',
 'mm': 'mil·límetre',
 'núm': 'número',
 'num': 'número',
 'pex': 'per exemple',
 'pàg': 'pàgina',
 'pl': 'plaça',
 'prof': 'professor',
 'ref': 'referència',
 'trad': 'traducció',
 'vs': 'versus',
 }

acronyms_dict = {"psoe": "pe soe", # acronyms that are not pronounced as a word (in this case, "keep initials", neither letter by letter)
                 "fnac": "efnac",
                 "dgaia": "degaia",
                 "psuc": "pe suc",
                 "psan": "pe san"
}

# TODO: add roman nums
roman_nums = {"ii": "segon",
                "iii": "tercer",
                "iiii": "quatre",
                "iv": "quart",  
                "vii": "setè",
                "viii": "vuitè",
                "xi" : "onze",
                "xii" : "dotze",
                "xiii" : "tretze",
                "xiv" : "catorze",
                "xv" : "quinze",
                "xvi" : "setze",
                "xvii" : "disset",
                "xviii" : "divuit",
                "xix" : "dinou",
                "xx" : "vint",
                "xxi" : "vint-i-un",
                "xxii" : "vint-i-dos",
                "xxiii" : "vint-i-tres",
                "xxiv" : "vint-i-quatre",
                "xxv" : "vint-i-cinc",
                "xxvi" : "vint-i-sis",
                "xxvii" : "vint-i-set",
                "xxviii" : "vint-i-vuit",
                "xxix" : "vint-i-nou",
                "xxx" : "trenta",
                "xxxi" : "trenta-un",
                "xxxii" : "trenta-dos",
                "xxxiii" : "trenta-tres",
                "xxxiv" : "trenta-quatre",
                "xxxv" : "trenta-cinc",
                "xxxvi" : "trenta-sis",
                "xxxvii" : "trenta-set",
                "xxxviii" : "trenta-vuit",
                "xxxix" : "trenta-nou",
                "xl" : "quaranta",
                "xli" : "quaranta-un",
                "xlii" : "quaranta-dos",
                "xliii" : "quaranta-tres",
                "xliv" : "quaranta-quatre",
                "xlv" : "quaranta-cinc",
                "xlvi" : "quaranta-sis",
                "xlvii" : "quaranta-set",
                "xlviii" : "quaranta-vuit",
                "xlix" : "quaranta-nou",
                "lii" : "cinquanta-dos",
                "liii" : "cinquanta-tres",
                "liv" : "cinquanta-quatre",
                "lv" : "cinquanta-cinc",
                "lvi" : "cinquanta-sis",
                "lvii" : "cinquanta-set",
                "lviii" : "cinquanta-vuit",
                "lix" : "cinquanta-nou",
                "lx" : "seixanta",
                "lxi" : "seixanta-un",
                "lxii" : "seixanta-dos",
                "lxiii" : "seixanta-tres",
                "lxiv" : "seixanta-quatre",
                "lxv" : "seixanta-cinc",
                "lxvi" : "seixanta-sis",
                "lxvii" : "seixanta-set",
                "lxviii" : "seixanta-vuit",
                "lxix" : "seixanta-nou",
                "lxx" : "setanta",
                "lxxi" : "setanta-un",
                "lxxii" : "setanta-dos",
                "lxxiii" : "setanta-tres",
                "lxxiv" : "setanta-quatre",
                "lxxv" : "setanta-cinc",
                "lxxvi" : "setanta-sis",
                "lxxvii" : "setanta-set",
                "lxxviii" : "setanta-vuit",
                "lxxix" : "setanta-nou",
                "lxxx" : "vuitanta",
                "lxxxi" : "vuitanta-un",
                "lxxxii" : "vuitanta-dos",
                "lxxxiii" : "vuitanta-tres",
                "lxxxiv" : "vuitanta-quatre",
                "lxxxv" : "vuitanta-cinc",
                "lxxxvi" : "vuitanta-sis",
                "lxxxvii" : "vuitanta-set",
                "lxxxviii" : "vuitanta-vuit",
                "lxxxix" : "vuitanta-nou",
                "xc" : "noranta",
                "xci" : "noranta-un",
                "xcii" : "noranta-dos",
                "xciii" : "noranta-tres",
                "xciv" : "noranta-quatre",
                "xcv" : "noranta-cinc",
                "xcvi" : "noranta-sis",
                "xcvii" : "noranta-set",
                "xcviii" : "noranta-vuit",
                "xcix" : "noranta-nou"
              }


letters = {"A": "a",
"B": "be",
"C": "ce",
"Ç": "ce trencada",
"D": "de",
"E": "e",
"F": "efa",
"G": "ge",
"H": "hac",
"I": "i",
"J": "jota",
"K": "ca",
"L": "ela",
"M": "ema",
"N": "ena",
"O": "o",
"P": "pe",
"Q": "cu",
"R": "erra",
"S": "essa",
"T": "te",
"U": "u",
"V": "ve",
"W": "ve doble",
"X": "ics",
"Y": "i grega",
"Z": "zeta"
}

