import string
import re

### accepted chars and language-specific cleaning function
accepted_chars = string.ascii_lowercase + "àèìòùáéíóúäëïöüñçâêîôû'’ 0123456789" # todo: remove 0-9

def lang_cleaning_text(text):
    return text    

### special characters

ordinals = {"℃": "grados Celsius",
            "°C": "grados Celsius",
            "ºC": "grados Celsius",
            "℉": "grados Farenheit",
            "°F": "grados Farenheit",
            "ºF": "grados Farenheit",
            "1o": "primero", # todo: primer/primero, tercer/tercero
            "1ra": "primera",
            "1a": "primera",
            "2ndo": "segundo",
            "2nda": "segunda",
            "2o": "segundo",
            "2a": "segunda",
            "3o": "tercer",
            "3a": "tercera",
            "3ro": "tercer",
            "3ra": "tercera",
            "4o": "cuarto",
            "4a": "cuarta",
            "4to": "cuarto",
            "4ta": "cuarta",
            "5o": "quinto",
            "5a": "quinta",
            "1º": "primero",
            "1ª": "primera",
            "2º": "segundo",
            "2ª": "segunda",
            "3º": "tercero",
            "3ª": "tercera",
            "4º": "cuarto",
            "4ª": "cuarta",
            "5º": "quinto",
            "5ª": "quinta"
            }

currency = {"€": "euros", # todo: sing/pl
    "$": "dólares",
    "¥": "yenes",
    "£": "libras"}

dots_and_commas = {
    ".": "punto",
    ",": "coma",
}
phisics_and_maths = {  
    "°": "grados",
    "+": "más",
    "=": "igual a",
    ">": "mayor que",
    "<": "menor que",
    "%": "por ciento",
    "ħ": "constante de Planck reducida",
    "µ": "micro",
    "𝜆": "Lambda",
    "∑": "sumatorio",
    "≈": "aproximadamente igual a",
    "≠": "distinto a",
    "≥": "mayor o igual a",
    "≤": "menor o igual a ",
    "∞": "infinito",
    "√": "raíz cuadrada",
    "²": "al cuadrado",
    "³": "al cubo",
    "×": "multiplicado por",
    "÷": "dividido por",
    "±": "más o menos",
    "∫": "integral",
    "∂": "derivativa parcial",
    "∇": "nabla",
    "≡": "congruente a",
    "≜": "definido como",
    "⁰": "superíndice zero",
    "ⁱ": "superíndice uno",
    "ⁿ": "superíndice ene",
    "⁻": "superíndice menos",
    "₀": "subíndice theta",
    "𝑓": "función efe",
    "𝑥": "equis",
    "ˣ": "equis"}

greek_letters = {

"Α": "alfa",
"Β": "beta",
"Γ": "gamma",
"Δ": "delta",
"Ε": "épsilon",
"Ζ": "dseta",
"Η": "eta",
"Θ": "zeta",
"Ι": "iota",
"Κ": "kappa",
"Λ": "lambda",
"Μ": "mi",
"Ν": "ni",
"Ξ": "xi",
"Ο": "ómicron",
"Π": "pi",
"Ρ": "ro",
"Σ": "sigma",
"Τ": "tau",
"Υ": "ípsilon",
"Φ": "fi",
"Χ": "ji",
"Ψ": "psi",
"Ω": "omega",

"α": "alfa",
"β": "beta",
"γ": "gamma",
"δ": "delta",
"ε": "épsilon",
"ζ": "dseta",
"η": "eta",
"θ": "zeta",
"ι": "iota",
"κ": "kappa",
"λ": "lambda",
"μ": "mi",
"ν": "ni",
"ξ": "xi",
"ο": "ómicron",
"π": "pi",
"ρ": "ro",
"σ": "sigma",
"τ": "tau",
"υ": "ípsilon",
"φ": "phi",
"χ": "chi",
"ψ": "psi",
"ω": "omega"}

### more than one character
abr_dict =  {
 'ac': 'entes de Cristp',
 'am': 'ante meridiem',
 'adj': 'adjetivo',
 'adm': 'administración',
 'adv': 'adverbio',
 'agr': 'agricultura',
 'ant': 'anterior',
 'aprox': 'aproximadamente',
 'arq': 'arquitecto',
 'atm': 'atmósfera',
 'aux': 'auxiliar',
 'av': 'avenida',
 'avda': 'avenida',
 'bach': 'bachillerato',
 'bibl': 'biblioteca',
 'cit': 'citado',
 'cm': 'centímetro',
 'coord': 'coordinador',
 'dc': 'después de Cristo',
 'd/d': 'dies data',
 'dep': 'departamento',
 'dest': 'destinatario',
 'disp': 'disposición',
 'doc': 'documento',
 'dr': 'doctor',
 'dra': 'doctora',
 'eg': 'exempli gratia',
 'edif': 'edificio',
 'ent': 'entresuelo',
 'esp': 'españa',
 'etc': 'etcétera',
 'ext': 'exterior',
 'fig': 'figura',
 'fm': 'freqüencia modulada',
 'fol': 'folio',
 'fr': 'francés',
 'gr': 'gramo',
 'gral': 'general',
 'hab': 'habitación',
 'hm': 'hectómetros',
 'inst': 'instituto',
 'int': 'interior',
 'kg': 'quilogramos',
 'km': 'quilómetros',
 'km/h': 'quilómetros por hora',
 'mph': 'millas por hora',
 'lat': 'latitud',
 'long': 'longitud',
 'max': 'máximo',
 'mm': 'milímetro',
 'n/d': 'no disponible',
 'n/p': 'no present',
 'núm': 'número',
 'pex': 'por ejemplo',
 'pm': 'post meridiem',
 'pm': 'post meridiem',
 'pag': 'página',
 'pd': 'posdata',
 'pl': 'plaza',
 'prof': 'profesor',
 'ref': 'referencia',
 's/n': 'sin número',
 'trad': 'traducción',
 'var': 'variable',
 'vs': 'versus',
 "lun": "lunes",
 "mier": "miércoles",
 "jue": "jueves",
 "vier": "viernes",
 "sab": "sábado",
 "dom": "domingo",
 "feb": "febrero",
 "abr": "abril",
 "may": "mayo",
 "jun": "junio",
 "jul": "julio",
 "sep": "septiembre",
 "oct": "octubre",
 "nov": "noviembre"
 }

acronyms_dict = {"psoe": "pe soe", # acronyms that are not pronounced as a word (in this case, "keep initials", neither letter by letter)
                 "fnac": "efnac",
                 "dgaia": "degaia",
                 "psuc": "pe suc",
                 "psan": "pe san"
}

keep_initials = ["iec", "pime", "unesco", "renfe", "pimes", "afa", "afas", "ser", "tic", "pib", "erto", "mena", "poum", "vox", "ceo", "coi",
                 "oms", "aie", "soc", "pas", "ave", "mes", "macba", "crae", "onu", "fama","acatur", "agbar", "rac", "mat", "acab", "cap",
                 "adif", "dui", "loapa", "pimec", "pac", "bei", "vao", "icub", "faada", "ampa", "uspac", "ustec", "iva", "uci", "cac", "coac", "caoc",
                 "sim", "boe", "cram", "centa", "eta", "sareb",
                 "afes", "once", "affac", "acapps", "cup", "ciu", "acció", "sem", "erc"] # acronyms that are pronounced as a word

# TODO: add roman nums
roman_nums = {"II": "segundo",
              "III": "tercero",
              "IIII": "cuatro",
              "IV": "quarto",
              "VI": "sexto",  
              "VII": "séptimo",
              "VIII": "octavo",
              "IX": "noveno",
              "X": "décimo",
              }

follow_proper_name = {
    "I": "primero",
    "V": "quinto"
}

letters = {"A": "a",
"B": "be",
"C": "ce",
"D": "de",
"E": "e",
"F": "efe",
"G": "ge",
"H": "hache",
"I": "i",
"J": "jota",
"K": "ca",
"L": "ele",
"M": "eme",
"N": "ene",
"O": "o",
"P": "pe",
"Q": "cu",
"R": "erre",
"S": "ese",
"T": "te",
"U": "u",
"V": "uve",
"W": "uve doble",
"X": "equis",
"Y": "y grega",
"Z": "zeta"}

